---
apiVersion: v1
kind: Service
metadata:
  namespace: examples-namespaced-flux
  name: hello-kubernetes-first
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hello-kubernetes-first
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: examples-namespaced-flux
  name: hello-kubernetes-first
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-kubernetes-first
  template:
    metadata:
      labels:
        app: hello-kubernetes-first
    spec:
      containers:
        - name: hello-kubernetes
          image: paulbouwer/hello-kubernetes:1.7
          ports:
            - containerPort: 8080
          env:
            - name: MESSAGE
              value: Hello from the first deployment!
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-kubernetes-ingress
  namespace: examples-namespaced-flux
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - hello-k8s.examples.svc.dev.lightricks.com
      secretName: hello-k8s
  rules:
    - host: hello-k8s.examples.svc.dev.lightricks.com
      http:
        paths:
          - backend:
              serviceName: hello-kubernetes-first
              servicePort: 80
