apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: examples-namespaced-flux
spec:
  chart:
    name: podinfo
    repository: s3://lightricks-helm-repo/simsimy
    version: 4.1.1
  releaseName: podinfo
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 4.0.6
    ingress:
      enabled: True
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - podinfo.examples.svc.dev.lightricks.com
      tls:
        - hosts:
            - podinfo.examples.svc.dev.lightricks.com
          secretName: podinfo-k8s